"""empty message

Revision ID: 250649f37432
Revises: c1ee75b3c834
Create Date: 2023-12-26 09:45:37.624227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '250649f37432'
down_revision = 'c1ee75b3c834'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto_seco', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Notas', sa.String(length=300), nullable=False))
        batch_op.alter_column('Formato',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=80),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto_seco', schema=None) as batch_op:
        batch_op.alter_column('Formato',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=300),
               existing_nullable=False)
        batch_op.drop_column('Notas')

    # ### end Alembic commands ###
