"""empty message

Revision ID: 44e874799e9d
Revises: 504f4e1cd2f3
Create Date: 2023-12-26 10:02:04.919744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44e874799e9d'
down_revision = '504f4e1cd2f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto_seco', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Nombre', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('Peso_cantidad', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('Formato', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('Notas', sa.String(length=300), nullable=False))
        batch_op.drop_constraint('producto_seco_nombre_key', type_='unique')
        batch_op.create_unique_constraint(None, ['Nombre'])
        batch_op.drop_column('notas')
        batch_op.drop_column('peso_cantidad')
        batch_op.drop_column('nombre')
        batch_op.drop_column('formato')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto_seco', schema=None) as batch_op:
        batch_op.add_column(sa.Column('formato', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('nombre', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('peso_cantidad', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('notas', sa.VARCHAR(length=300), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('producto_seco_nombre_key', ['nombre'])
        batch_op.drop_column('Notas')
        batch_op.drop_column('Formato')
        batch_op.drop_column('Peso_cantidad')
        batch_op.drop_column('Nombre')

    # ### end Alembic commands ###
