"""empty message

Revision ID: 703ca7f4f1d1
Revises: b237eafef6fe
Create Date: 2023-12-29 08:19:59.806767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '703ca7f4f1d1'
down_revision = 'b237eafef6fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto_seco', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto_seco', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
