"""empty message

Revision ID: c1ee75b3c834
Revises: bfc463efe301
Create Date: 2023-12-26 09:44:47.350805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1ee75b3c834'
down_revision = 'bfc463efe301'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto_seco', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Nombre', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('Peso_cantidad', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('Formato', sa.String(length=300), nullable=False))
        batch_op.drop_constraint('producto_seco_email_key', type_='unique')
        batch_op.create_unique_constraint(None, ['Nombre'])
        batch_op.drop_column('password')
        batch_op.drop_column('email')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto_seco', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('producto_seco_email_key', ['email'])
        batch_op.drop_column('Formato')
        batch_op.drop_column('Peso_cantidad')
        batch_op.drop_column('Nombre')

    # ### end Alembic commands ###
